# Generated by Django 3.0.4 on 2020-04-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobShow', '0002_jobsshow_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsshow',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobsshow',
            name='domain',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
