# Generated by Django 3.0.4 on 2020-04-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobShow', '0003_auto_20200404_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsshow',
            old_name='group',
            new_name='field',
        ),
    ]
