# Generated by Django 3.0.4 on 2020-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='image',
            field=models.CharField(default=None, max_length=225),
        ),
    ]
